import Link from "next/link";

const architecture=[
 ["CareFlow source","A purpose-built domain-specific language represents workflows in a compact, readable form."],
 ["Lexer + parser","Source text is tokenized and converted into a structured abstract syntax representation."],
 ["Validator","Semantic checks catch invalid workflow definitions before simulation."],
 ["Interpreter","The runtime executes workflow logic, state transitions, timing, safety rules, and escalation behaviour."],
 ["Visualization","Studio and simulator workspaces expose workflow structure, runtime state, validation, and scenario behaviour."],
];
const features=[
 ["Custom DSL","Designed a language layer for expressing healthcare workflow logic instead of hard-coding every scenario directly into the UI."],
 ["Language tooling","Implemented lexer, parser, AST/type structures, validation, and interpretation as separate engineering layers."],
 ["Simulation runtime","Runs synthetic operational scenarios and exposes state changes, timing, escalation, and safety behaviour."],
 ["Studio workspace","Provides source editing, validation feedback, and workflow-diagram views so a user can inspect what the language describes."],
 ["Runtime visualization","Turns execution into an observable dashboard rather than leaving simulation behaviour hidden in code."],
 ["Automated tests","The repository includes dedicated tests for lexer, parser, validator, interpreter, types, and runtime visualization behaviour."],
];
const tools=[["Next.js + TypeScript","Web application and strongly typed implementation."],["Custom lexer/parser","Transforms CareFlow source into structured program representations."],["AST + type system","Defines the workflow language model and internal structures."],["Validator","Checks source and workflow semantics before execution."],["Interpreter","Executes the domain language and simulation rules."],["Vitest","Automated testing of language and runtime components."]];
const tests=["Lexer tokenization","Parser behaviour","Semantic validation","Interpreter execution","Type structures","Runtime visualization"];
export default function Page(){return <main className="min-h-screen bg-[#fbf8ff] text-purple-950">
<nav className="border-b border-purple-100 bg-white/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-8"><Link href="/" className="font-serif text-2xl font-bold">Zainab<span className="text-purple-600">.</span></Link><Link href="/#projects" className="rounded-full bg-purple-700 px-5 py-2 font-semibold text-white">All Projects</Link></div></nav>
<section className="mx-auto max-w-7xl px-6 py-20 md:px-8"><p className="inline-flex rounded-full border border-purple-200 bg-white px-4 py-2 text-sm font-bold text-purple-700">Software Engineering + Simulation</p><h1 className="mt-6 font-serif text-5xl font-bold md:text-7xl">CareFlow Studio<span className="block text-purple-600">A workflow language and simulation environment</span></h1><p className="mt-6 max-w-4xl text-lg leading-8 text-purple-950/70">A software-engineering project for representing and simulating healthcare workflows through a custom domain-specific language. Instead of treating the project as only a dashboard, I built the language-processing and runtime layers behind it: lexer, parser, validation, interpreter, synthetic scenarios, and observable simulation views.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://github.com/Zlawal79/careflow-studio" target="_blank" className="rounded-full bg-purple-700 px-6 py-3 font-bold text-white">View GitHub</a><Link href="/" className="rounded-full border border-purple-200 bg-white px-6 py-3 font-bold text-purple-800">Portfolio</Link></div></section>
<section className="mx-auto grid max-w-7xl gap-5 px-6 py-8 md:grid-cols-2 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8 shadow-sm"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-600">The Problem & Why I Built It</p><h2 className="mt-3 font-serif text-3xl font-bold">Complex workflows are difficult to reason about when their rules are scattered.</h2><p className="mt-5 leading-8 text-purple-950/70">Timing, escalation, safety conditions, dependencies, and operational decisions can become difficult to reason about when they are scattered through application logic or described only informally. I wanted to explore a more software-engineering-focused solution: represent the workflow itself as a structured language that can be validated, executed, tested, and visualized.</p></div><div className="rounded-[2rem] bg-purple-950 p-8 text-white"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-300">Engineering Goal</p><h2 className="mt-3 font-serif text-3xl font-bold">Make workflow logic executable and inspectable.</h2><p className="mt-5 leading-8 text-purple-100">The project separates language definition, parsing, validation, execution, and visualization so each layer can be reasoned about and tested independently.</p></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><p className="text-center text-sm font-bold uppercase tracking-[.18em] text-purple-600">System Architecture</p><h2 className="mt-3 text-center font-serif text-4xl font-bold">From workflow text to simulation</h2><div className="mt-10 grid gap-4 md:grid-cols-5">{architecture.map(([n,d])=><div key={n} className="rounded-3xl border border-purple-100 bg-white p-6 shadow-sm"><h3 className="font-bold text-purple-800">{n}</h3><p className="mt-3 text-sm leading-6 text-purple-950/65">{d}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><h2 className="text-center font-serif text-4xl font-bold">What I built</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{features.map(([n,d])=><div key={n} className="rounded-3xl border border-purple-100 bg-white p-7 shadow-sm"><h3 className="text-xl font-bold text-purple-800">{n}</h3><p className="mt-3 leading-7 text-purple-950/65">{d}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] bg-purple-950 p-8 text-white"><h2 className="font-serif text-4xl font-bold">Technologies & implementation</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{tools.map(([n,d])=><div key={n} className="rounded-2xl bg-white/10 p-5"><h3 className="text-xl font-bold">{n}</h3><p className="mt-2 leading-7 text-purple-100">{d}</p></div>)}</div></div></section>
<section className="mx-auto grid max-w-7xl gap-5 px-6 py-16 md:grid-cols-2 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8"><h2 className="font-serif text-3xl font-bold">Testing</h2><p className="mt-4 leading-7 text-purple-950/65">I treated the language/runtime as software infrastructure rather than only UI functionality. Automated tests cover the core processing stages.</p><div className="mt-6 flex flex-wrap gap-2">{tests.map(x=><span key={x} className="rounded-full bg-purple-50 px-4 py-2 font-semibold text-purple-700">{x}</span>)}</div></div><div className="rounded-[2rem] border border-purple-100 bg-white p-8"><h2 className="font-serif text-3xl font-bold">What I learned</h2><p className="mt-5 leading-8 text-purple-950/70">CareFlow Studio pushed me beyond standard CRUD application development. It strengthened my understanding of language design, parsing, validation, interpreters, stateful simulation, testable architecture, and the importance of making complex runtime behaviour visible to users.</p></div></section>
</main>}