import Link from "next/link";

const pipeline=[
 ["1. Collect","Use July 2026 U.S. BTS Reporting Carrier On-Time Performance flight records and hourly historical weather observations."],
 ["2. Clean","Standardize flight and weather fields, remove unusable records, and prepare timestamps and airport identifiers."],
 ["3. Match","Join each eligible flight to weather conditions at its origin airport and departure time."],
 ["4. Engineer","Create time, route, airline, airport, and weather features while excluding outcome information that would leak the target."],
 ["5. Train","Fit an interpretable Logistic Regression baseline and a Random Forest model for nonlinear relationships."],
 ["6. Evaluate","Compare held-out precision, recall, F1, ROC-AUC, confusion matrix, ROC/PR curves, and feature importance."],
];
const metrics=[["631,970","Raw flight records"],["308,396","Matched flight-weather records"],["99.98%","Weather matching rate"],["0.7427","Random Forest ROC-AUC"]];
const models=[
 ["Logistic Regression","65.96%","47.11%","66.29%","0.5508","0.7157"],
 ["Random Forest","68.09%","49.49%","67.11%","0.5697","0.7427"],
];
const features=["Scheduled departure hour","Time of day","Day of week","Airline","Origin and destination airports","Temperature","Relative humidity","Precipitation","Wind conditions","Weather condition codes"];
const tools=[["Python","End-to-end data processing and model workflow."],["Pandas","Cleaning, transformation, merging, and feature preparation."],["scikit-learn","Preprocessing, Logistic Regression, Random Forest, and evaluation."],["Streamlit","Interactive three-page application for explanation, prediction, and results."],["Matplotlib + Plotly","Evaluation artifacts and interactive model visualizations."],["joblib","Persisting trained model artifacts for application use."]];
export default function Page(){return <main className="min-h-screen bg-[#fbf8ff] text-purple-950">
<nav className="border-b border-purple-100 bg-white/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-8"><Link href="/" className="font-serif text-2xl font-bold">Zainab<span className="text-purple-600">.</span></Link><Link href="/#projects" className="rounded-full bg-purple-700 px-5 py-2 font-semibold text-white">All Projects</Link></div></nav>
<section className="mx-auto max-w-7xl px-6 py-20 md:px-8"><p className="inline-flex rounded-full border border-purple-200 bg-white px-4 py-2 text-sm font-bold text-purple-700">Data Science + Machine Learning</p><h1 className="mt-6 font-serif text-5xl font-bold md:text-7xl">SkyPredict<span className="block text-purple-600">Flight-delay prediction with flight and weather data</span></h1><p className="mt-6 max-w-4xl text-lg leading-8 text-purple-950/70">An end-to-end machine-learning project that combines real U.S. flight records with hourly weather observations to test whether information available before departure can help predict a 15+ minute departure delay.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://github.com/Zlawal79/skypredict" target="_blank" className="rounded-full bg-purple-700 px-6 py-3 font-bold text-white">View GitHub</a><Link href="/" className="rounded-full border border-purple-200 bg-white px-6 py-3 font-bold text-purple-800">Portfolio</Link></div></section>
<section className="mx-auto grid max-w-7xl gap-5 px-6 py-8 md:grid-cols-2 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8 shadow-sm"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-600">The Problem & Motivation</p><h2 className="mt-3 font-serif text-3xl font-bold">Can flight and weather information predict departure delay?</h2><p className="mt-5 leading-8 text-purple-950/70">Flight delays affect passengers and transportation operations, but many contributing factors are only known after a disruption occurs. I wanted to test how much useful signal exists in information available beforehand. I framed a 15+ minute departure delay as a binary classification problem and built an evidence-based ML workflow around that question.</p></div><div className="rounded-[2rem] bg-purple-950 p-8 text-white"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-300">Leakage Control</p><h2 className="mt-3 font-serif text-3xl font-bold">Only information available before the outcome.</h2><p className="mt-5 leading-8 text-purple-100">Actual departure information and recorded delay causes are excluded from predictors. This keeps the evaluation focused on information that could reasonably be known before departure rather than allowing the model to see the answer indirectly.</p></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] bg-purple-700 p-8 text-white md:p-10"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-200">Dataset & Evidence</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([v,l])=><div key={l} className="rounded-2xl bg-white/10 p-5"><p className="font-serif text-3xl font-bold">{v}</p><p className="mt-2 text-purple-100">{l}</p></div>)}</div></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><p className="text-center text-sm font-bold uppercase tracking-[.18em] text-purple-600">End-to-End Pipeline</p><h2 className="mt-3 text-center font-serif text-4xl font-bold">How I built SkyPredict</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{pipeline.map(([n,d])=><div key={n} className="rounded-3xl border border-purple-100 bg-white p-6 shadow-sm"><h3 className="text-xl font-bold text-purple-800">{n}</h3><p className="mt-3 leading-7 text-purple-950/65">{d}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8 shadow-sm"><h2 className="font-serif text-4xl font-bold">Feature engineering</h2><p className="mt-4 max-w-4xl leading-7 text-purple-950/65">I transformed raw flight and weather fields into 18 model-ready features covering schedule, airport, airline, temporal, and meteorological context.</p><div className="mt-6 flex flex-wrap gap-2">{features.map(x=><span key={x} className="rounded-full bg-purple-50 px-4 py-2 font-semibold text-purple-700">{x}</span>)}</div></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><h2 className="text-center font-serif text-4xl font-bold">Held-out model evaluation</h2><p className="mx-auto mt-4 max-w-3xl text-center leading-7 text-purple-950/60">Because 68.52% of merged flights were not delayed, I did not treat accuracy alone as proof of model quality. I compared recall, precision, F1, and ROC-AUC as well.</p><div className="mt-10 overflow-x-auto rounded-3xl border border-purple-100 bg-white p-6 shadow-sm"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-purple-100">{["Model","Accuracy","Precision","Recall","F1","ROC-AUC"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{models.map(r=><tr key={r[0]} className="border-b border-purple-50 last:border-0">{r.map((x,i)=><td key={i} className={"p-4 "+(i===0?"font-bold":"")}>{x}</td>)}</tr>)}</tbody></table></div><p className="mt-5 text-center font-semibold text-purple-700">Random Forest produced the stronger held-out results, including ROC-AUC 0.7427 and delayed-flight recall 67.11%.</p></section>
<section className="mx-auto grid max-w-7xl gap-5 px-6 py-16 md:grid-cols-2 md:px-8"><div className="rounded-[2rem] bg-purple-950 p-8 text-white"><h2 className="font-serif text-3xl font-bold">Explainability</h2><p className="mt-5 leading-8 text-purple-100">Feature importance showed departure hour, morning/evening indicators, temperature, weather condition, and relative humidity among the stronger model inputs. I present these as predictive importance—not evidence that they directly cause delays.</p></div><div className="rounded-[2rem] border border-purple-100 bg-white p-8"><h2 className="font-serif text-3xl font-bold">Interactive application</h2><p className="mt-5 leading-8 text-purple-950/70">The Streamlit app has three sections: About & How It Works, Try It Out, and Results & Insights. Users can enter a hypothetical flight scenario, inspect an estimated delay probability, and then explore the evaluation evidence behind the model.</p></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] bg-purple-700 p-8 text-white"><h2 className="font-serif text-4xl font-bold">Technologies & implementation</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{tools.map(([n,d])=><div key={n} className="rounded-2xl bg-white/10 p-5"><h3 className="text-xl font-bold">{n}</h3><p className="mt-2 leading-7 text-purple-100">{d}</p></div>)}</div></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8"><h2 className="font-serif text-4xl font-bold">What I learned</h2><p className="mt-5 max-w-5xl leading-8 text-purple-950/70">SkyPredict strengthened my understanding of real-world data integration, leakage prevention, class imbalance, model comparison, explainability, and communicating performance responsibly. The biggest lesson was that a credible ML project needs a reproducible pipeline and honest evaluation—not just a single accuracy number.</p></div></section>
</main>}