import Link from "next/link";
const features=["631,970 raw flight records processed","308,396 matched flight-weather observations","Logistic Regression baseline and Random Forest comparison","Held-out evaluation using precision, recall, F1 and ROC-AUC","Random Forest ROC-AUC of 0.7427","Streamlit interface for prediction and model insights"];
const tools=["Python","Pandas","scikit-learn","Streamlit","Matplotlib","Plotly"];
export default function Page(){return <main className="min-h-screen bg-[#fbf8ff] text-purple-950">
<nav className="border-b border-purple-100 bg-white/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-8"><Link href="/" className="font-serif text-2xl font-bold">Zainab<span className="text-purple-600">.</span></Link><Link href="/#projects" className="rounded-full bg-purple-700 px-5 py-2 font-semibold text-white">All Projects</Link></div></nav>
<section className="mx-auto max-w-7xl px-6 py-20 md:px-8"><p className="inline-flex rounded-full border border-purple-200 bg-white px-4 py-2 text-sm font-bold text-purple-700">Data Science + Machine Learning</p><h1 className="mt-6 font-serif text-5xl font-bold md:text-7xl">SkyPredict<span className="block text-purple-600">Flight-delay prediction with flight and weather data</span></h1><p className="mt-6 max-w-4xl text-lg leading-8 text-purple-950/70">SkyPredict is an end-to-end machine learning project that combines public U.S. flight records with hourly weather observations to investigate whether information available before departure can help predict a 15+ minute departure delay.</p><div className="mt-8 flex gap-3"><a href="https://github.com/Zlawal79/skypredict" target="_blank" className="rounded-full bg-purple-700 px-6 py-3 font-bold text-white">View GitHub</a><Link href="/" className="rounded-full border border-purple-200 bg-white px-6 py-3 font-bold text-purple-800">Portfolio</Link></div></section>
<section className="mx-auto max-w-7xl px-6 py-8 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8 shadow-sm"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-600">The Challenge</p><h2 className="mt-3 font-serif text-4xl font-bold">Problem statement</h2><p className="mt-5 max-w-5xl leading-8 text-purple-950/70">Flight delays arise from many interacting factors. The project tests whether scheduled flight information, airport context, time features, and historical weather contain useful predictive signal without using outcome information that would create target leakage.</p></div></section>
<section className="mx-auto max-w-7xl px-6 py-20 md:px-8"><h2 className="text-center font-serif text-4xl font-bold">What the project demonstrates</h2><div className="mt-10 grid gap-4 md:grid-cols-2">${features.map(x=><div key={x} className="rounded-2xl border border-purple-100 bg-white p-5 shadow-sm">• {x}</div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] bg-purple-950 p-8 text-white"><h2 className="font-serif text-4xl font-bold">Tools & Methods</h2><div className="mt-7 flex flex-wrap gap-3">${tools.map(x=><span key={x} className="rounded-full bg-white/10 px-4 py-2 font-semibold">{x}</span>)}</div></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8"><h2 className="font-serif text-4xl font-bold">What I focused on</h2><p className="mt-5 max-w-4xl leading-8 text-purple-950/70">I approached this project as an engineering portfolio piece: define the problem clearly, build a structured technical workflow, test the behaviour, communicate limitations, and make the result understandable to someone who did not build the system.</p></div></section>
</main>}