import Link from "next/link";

const features=[
  ["Multi-format data ingestion","Upload CSV, TSV, XLSX, or XLS files and automatically profile schema, types, missing values, duplicates, outliers, and correlations."],
  ["Grounded data Q&A","Questions are answered from deterministic calculations and verified dataset context before AI is used to explain the result."],
  ["Multi-file business analysis","Orders, products, and refunds can be joined with key validation and an audit trail that prevents unmatched or duplicate records from silently distorting totals."],
  ["Interactive visualizations","Line, bar, scatter, pie, histogram, and box plots turn uploaded data into explorable evidence, with chart recommendations when useful."],
  ["Decision-ready reporting","Generate executive summaries, evidence, limitations, areas to investigate, cleaned data, PDF/Excel reports, and downloadable business charts."],
  ["Responsible AI design","The interface separates calculated observations from interpretation, keeps API secrets server-side, and remains usable in deterministic mode when AI is unavailable."],
];
const tools=[
  ["TypeScript + React","Application interface and typed product logic."],
  ["Next.js-compatible runtime","Full-stack application structure and server-side AI endpoint."],
  ["SheetJS","Spreadsheet ingestion and Excel report generation."],
  ["Recharts","Interactive business and analytical visualizations."],
  ["PDF-lib","Client-side PDF report generation."],
  ["Gemini API","Optional structured explanations constrained by verified analysis context."],
  ["Node tests + Vite SSR","Calculation, edge-case, and application testing."],
];
const workflow=[
  ["1. Ingest","Parse uploaded files locally and identify schema, types, quality issues, and dataset roles."],
  ["2. Validate","Check joins, source keys, duplicate IDs, invalid values, and assumptions before calculating business metrics."],
  ["3. Calculate","Use deterministic analysis functions for revenue, COGS, profit, refunds, net revenue, profiling, correlations, and other evidence."],
  ["4. Explain","Pass a compact verified context to the optional AI layer so narrative answers remain tied to calculated evidence."],
  ["5. Communicate","Present dashboards, charts, limitations, investigation prompts, cleaned exports, and downloadable reports."],
];
const evidence=[
  ["32,313","Unique orders in the verified e-commerce case study"],
  ["$1.94M","Gross revenue calculated from the case-study files"],
  ["1,731 / 1,731","Refund rows successfully matched"],
  ["4 / 4","Product IDs successfully matched"],
];
const tests=["CSV quoting and duplicate headers","Empty datasets and missing required columns","Currency-formatted and invalid values","Duplicate business IDs and unmatched joins","Refund double-counting prevention","Grounded question routing and project-plan risk calculations"];
export default function Page(){return <main className="min-h-screen bg-[#fbf8ff] text-purple-950">
<nav className="border-b border-purple-100 bg-white/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-8"><Link href="/" className="font-serif text-2xl font-bold">Zainab<span className="text-purple-600">.</span></Link><Link href="/#projects" className="rounded-full bg-purple-700 px-5 py-2 font-semibold text-white">All Projects</Link></div></nav>
<section className="mx-auto max-w-7xl px-6 py-20 md:px-8"><p className="inline-flex rounded-full border border-purple-200 bg-white px-4 py-2 text-sm font-bold text-purple-700">AI + Data Analytics · Full-Stack Engineering</p><h1 className="mt-6 font-serif text-5xl font-bold md:text-7xl">DataSage<span className="block text-purple-600">Grounded AI for practical data exploration</span></h1><p className="mt-6 max-w-4xl text-lg leading-8 text-purple-950/70">A grounded data-analysis web application that turns spreadsheet files into verified metrics, interactive visualizations, cleaned exports, and AI-written explanations. I designed it so calculations happen before language generation, keeping important numerical claims traceable to the uploaded data.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://github.com/Zlawal79/datasage-ai" target="_blank" className="rounded-full bg-purple-700 px-6 py-3 font-bold text-white">View GitHub</a><Link href="/" className="rounded-full border border-purple-200 bg-white px-6 py-3 font-bold text-purple-800">Portfolio</Link></div></section>
<section className="mx-auto grid max-w-7xl gap-5 px-6 py-8 md:grid-cols-2 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8 shadow-sm"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-600">The Challenge</p><h2 className="mt-3 font-serif text-3xl font-bold">Useful data is not automatically useful insight.</h2><p className="mt-5 leading-8 text-purple-950/70">General-purpose AI can sound confident while getting calculations wrong, and manual spreadsheet analysis is slow for non-technical users. DataSage separates deterministic analysis from AI explanation so users can see evidence, formulas, join quality, assumptions, and limitations.</p></div><div className="rounded-[2rem] bg-purple-950 p-8 text-white"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-300">Why I cared about it</p><h2 className="mt-3 font-serif text-3xl font-bold">Ground the answer before generating the prose.</h2><p className="mt-5 leading-8 text-purple-100">I wanted the convenience of AI-assisted analysis without asking a user to blindly trust generated numbers. That led me to an auditable design: validate the files, calculate the evidence in code, and only then let the language model explain what the verified calculations show.</p></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><p className="text-center text-sm font-bold uppercase tracking-[.18em] text-purple-600">Architecture</p><h2 className="mt-3 text-center font-serif text-4xl font-bold">How DataSage works</h2><div className="mt-10 grid gap-4 md:grid-cols-5">{workflow.map(([n,d])=><div key={n} className="rounded-2xl border border-purple-100 bg-white p-5 shadow-sm"><h3 className="font-bold text-purple-800">{n}</h3><p className="mt-3 text-sm leading-6 text-purple-950/65">{d}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><h2 className="text-center font-serif text-4xl font-bold">What I built</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{features.map(([n,d])=><div key={n} className="rounded-3xl border border-purple-100 bg-white p-7 shadow-sm"><h3 className="text-xl font-bold text-purple-800">{n}</h3><p className="mt-3 leading-7 text-purple-950/65">{d}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] bg-purple-700 p-8 text-white md:p-10"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-200">Verified Case-Study Evidence</p><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{evidence.map(([v,l])=><div key={l} className="rounded-2xl bg-white/10 p-5"><p className="font-serif text-3xl font-bold">{v}</p><p className="mt-2 text-sm leading-6 text-purple-100">{l}</p></div>)}</div></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] bg-purple-950 p-8 text-white"><h2 className="font-serif text-4xl font-bold">Technologies & what they do</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{tools.map(([n,d])=><div key={n} className="rounded-2xl bg-white/10 p-5"><h3 className="text-xl font-bold">{n}</h3><p className="mt-2 leading-7 text-purple-100">{d}</p></div>)}</div></div></section>
<section className="mx-auto grid max-w-7xl gap-5 px-6 py-16 md:grid-cols-2 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8"><h2 className="font-serif text-3xl font-bold">Testing & reliability</h2><div className="mt-6 space-y-3">{tests.map(x=><p key={x} className="rounded-xl bg-purple-50 p-4">• {x}</p>)}</div></div><div className="rounded-[2rem] border border-purple-100 bg-white p-8"><h2 className="font-serif text-3xl font-bold">Limitations I communicate</h2><p className="mt-5 leading-8 text-purple-950/70">The app deliberately labels estimated net profit as an estimate, treats correlation as association rather than causation, requires human review for cleaning recommendations, and does not claim forecasting or statistical-significance testing that the current version does not perform.</p><h3 className="mt-7 text-xl font-bold">What this project taught me</h3><p className="mt-3 leading-7 text-purple-950/65">The strongest AI product is not the one that generates the most text; it is the one that can show where its claims came from. Building DataSage strengthened my full-stack, testing, data-quality, responsible-AI, and technical communication skills.</p></div></section>
</main>}