import Link from "next/link";

const story=[
 ["The problem","Network-flow datasets contain many measurements, but turning them into useful security decisions requires more than simply training a classifier. The output has to be understandable to the person investigating an alert."],
 ["Why I built it","I wanted a cybersecurity project that connected machine learning with the way security analysts actually review activity: classify traffic, surface suspicious behaviour, and communicate what the model is seeing through a SOC-style interface."],
 ["What I decided to build","SentinelML combines a structured intrusion-detection workflow with a dashboard designed around security monitoring. The goal is to move from raw flow records to an interpretable attack category rather than stopping at a notebook model."],
 ["The engineering challenge","The difficult part is keeping preprocessing, labels, model inputs, and dashboard output consistent. Security models can look impressive while hiding class imbalance, ambiguous labels, or preprocessing assumptions, so the project emphasizes transparent categories and reproducible testing."],
];
const pipeline=[
 ["1. Network-flow input","Work with structured flow-level records rather than packet payloads."],
 ["2. Prepare features","Clean and transform numerical network-flow attributes into model-ready inputs."],
 ["3. Map labels","Group traffic into understandable security categories: Normal, DoS/DDoS, Brute Force, Botnet, Port Scan, Web Attack, and Infiltration."],
 ["4. Train & test","Evaluate classification behaviour on held-out data rather than judging the system from training performance alone."],
 ["5. Surface alerts","Translate model output into a SOC-style monitoring view so suspicious traffic can be reviewed as security events."],
];
const categories=["Normal","DoS / DDoS","Brute Force","Botnet","Port Scan","Web Attack","Infiltration"];
const principles=[
 ["Transparent labels","Attack names are presented as human-readable security categories instead of opaque numeric classes."],
 ["Structured uploads","The interface is designed for the same type of structured network-flow features used by the model, avoiding claims that it can inspect arbitrary files or raw packet captures."],
 ["Evidence before claims","Performance should be communicated with the actual held-out metrics produced by the trained workflow; I do not present invented accuracy values in the portfolio."],
 ["Analyst-oriented output","Predictions are treated as decision-support signals for investigation, not proof that a host or user is malicious."],
];
const tools=[["Python","Data preparation, model experimentation, and security-analysis workflow."],["Machine Learning","Supervised classification of normal and malicious network-flow behaviour."],["CIC-IDS-2017","Public intrusion-detection dataset used as the basis for labelled flow examples."],["SOC Dashboard","Presents classifications and suspicious activity in an analyst-oriented interface."],["Data Visualization","Turns model/security output into patterns that can be reviewed quickly."],["Testing & Evaluation","Held-out evaluation and label-level inspection support more responsible model communication."]];
export default function Page(){return <main className="min-h-screen bg-[#fbf8ff] text-purple-950">
<nav className="border-b border-purple-100 bg-white/90"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 md:px-8"><Link href="/" className="font-serif text-2xl font-bold">Zainab<span className="text-purple-600">.</span></Link><Link href="/#projects" className="rounded-full bg-purple-700 px-5 py-2 font-semibold text-white">All Projects</Link></div></nav>
<section className="mx-auto max-w-7xl px-6 py-20 md:px-8"><p className="inline-flex rounded-full border border-purple-200 bg-white px-4 py-2 text-sm font-bold text-purple-700">Cybersecurity + Machine Learning</p><h1 className="mt-6 font-serif text-5xl font-bold md:text-7xl">SentinelML<span className="block text-purple-600">From network-flow data to security decisions</span></h1><p className="mt-6 max-w-4xl text-lg leading-8 text-purple-950/70">An intrusion-detection project that explores how machine learning can classify structured network traffic and turn model output into a SOC-style monitoring experience. I built it to connect the data-science side of intrusion detection with the communication and investigation needs of a security analyst.</p></section>
<section className="mx-auto max-w-7xl px-6 pb-8 md:px-8"><div className="grid gap-5 md:grid-cols-2">{story.map(([n,d],i)=><div key={n} className={"rounded-[2rem] p-7 shadow-sm "+(i===2?"bg-purple-950 text-white":"border border-purple-100 bg-white")}><p className={"text-sm font-bold uppercase tracking-[.18em] "+(i===2?"text-purple-300":"text-purple-600")}>{n}</p><p className={"mt-4 leading-8 "+(i===2?"text-purple-100":"text-purple-950/70")}>{d}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><p className="text-center text-sm font-bold uppercase tracking-[.18em] text-purple-600">System Workflow</p><h2 className="mt-3 text-center font-serif text-4xl font-bold">How SentinelML works</h2><div className="mt-10 grid gap-4 md:grid-cols-5">{pipeline.map(([n,d])=><div key={n} className="rounded-3xl border border-purple-100 bg-white p-6 shadow-sm"><h3 className="font-bold text-purple-800">{n}</h3><p className="mt-3 text-sm leading-6 text-purple-950/65">{d}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] bg-purple-700 p-8 text-white md:p-10"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-200">Classification Scope</p><h2 className="mt-3 font-serif text-4xl font-bold">Security categories the interface is designed to communicate</h2><div className="mt-7 flex flex-wrap gap-3">{categories.map(x=><span key={x} className="rounded-full bg-white/15 px-4 py-2 font-bold">{x}</span>)}</div></div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><h2 className="text-center font-serif text-4xl font-bold">Engineering decisions</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{principles.map(([n,d])=><div key={n} className="rounded-3xl border border-purple-100 bg-white p-7 shadow-sm"><h3 className="text-xl font-bold text-purple-800">{n}</h3><p className="mt-3 leading-7 text-purple-950/65">{d}</p></div>)}</div></section>
<section className="mx-auto max-w-7xl px-6 py-16 md:px-8"><div className="rounded-[2rem] bg-purple-950 p-8 text-white"><h2 className="font-serif text-4xl font-bold">Technologies & what they contribute</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{tools.map(([n,d])=><div key={n} className="rounded-2xl bg-white/10 p-5"><h3 className="text-xl font-bold">{n}</h3><p className="mt-2 leading-7 text-purple-100">{d}</p></div>)}</div></div></section>
<section className="mx-auto grid max-w-7xl gap-5 px-6 py-16 md:grid-cols-2 md:px-8"><div className="rounded-[2rem] border border-purple-100 bg-white p-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-600">Testing & Evidence</p><h2 className="mt-3 font-serif text-3xl font-bold">Evaluate the model, not just the demo.</h2><p className="mt-5 leading-8 text-purple-950/70">The project is structured around held-out testing and category-level interpretation. The portfolio intentionally avoids displaying a made-up headline accuracy while the final trained evaluation artifacts are being completed and verified.</p></div><div className="rounded-[2rem] border border-purple-100 bg-white p-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-purple-600">What I Learned</p><h2 className="mt-3 font-serif text-3xl font-bold">Cybersecurity ML is also a communication problem.</h2><p className="mt-5 leading-8 text-purple-950/70">SentinelML strengthened my understanding of intrusion-detection data, multiclass classification, security-oriented interfaces, and responsible model reporting. A useful security system has to make its outputs understandable enough for a person to investigate rather than treating the prediction as unquestionable truth.</p></div></section>
</main>}